{"name": "Тест на ошибку при  авторизации под несуществующим пользователем", "status": "passed", "description": "Вводим логин и пароль несуществующего пользователя и проверяем что получаем ошибку 401 и сообщение ", "start": 1747223372321, "stop": 1747223372558, "uuid": "a1065668-4ea6-4158-ad33-8a250a2faa04", "historyId": "d1d220f4b4df5ae6d7ab741caef8ee80", "testCaseId": "d1d220f4b4df5ae6d7ab741caef8ee80", "fullName": "tests.test_login_user.TestLoginUser#test_auth_with_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "6276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}